### ISSUE TITLE
Optimizing conv_layer to Use Less logical_units

### ISSUE THREAD

**Issue by EugLiu** [Codax2000/fir-cnn-rtl#48]

**Comment by Codax2000** [comment]
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/c50426a8-1459-44dd-ad00-0e0454dd6274)

Testbench working with 2x5 input, 2x3 kernel

**Comment by Codax2000** [comment]
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/f7121161-1899-4d17-b6f4-6fba67219057)

Block RAM utilization

**Comment by Codax2000** [comment]
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/40e38cba-b98b-4265-b6b1-ab58b13fbbd5)

CLB and LUT utilization. This will likely be lower on our board, since we have DSP slices.

**Comment by Codax2000** [comment]
Synthesis time:
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/4d4b4598-35b8-4a5c-a45a-52cd9552f9da)

**Comment by Codax2000** [comment]
Synthesis and implementation passing in Vivado for convolutional layer:
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/d92469f8-6934-483f-8aa4-41ffb4b39da8)

**Comment by Codax2000** [comment]
New post-synthesis simulation report:
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/08d7d916-6fb7-4f41-bcc9-98e2276a7a43)
Timing simulation fails hold time (as does synthesis timing report), but there is no clock tree, so wait for post-implementation simulation to sort out hold time violations.

Post-implementation simulation report:
![image](https://github.com/Codax2000/fir-cnn-rtl/assets/56089279/cd5f11e7-767b-41b1-ae8f-9918c4d80f02)

Timing constraints and implementation (for this testbench at least) are fully functional.
